Description feature
conorreedy/character-buidler pull request #4
Opened 2020-01-14 01:32 UTC by cusbus

there is a lot of work ahead on this one, but the base functionality is there.

you should be able to choose any of the backgrounds in the dropdown, then choose your proficiencies (skills, tools, languages). your background feature should pop up when you choose a bg

i also integrated the rules for creating custom backgrounds. briefly, you get to pick a variety of skills, tools, languages and then any background feature you want. this is represented correctly.

finally, there is a simple small set of inputs to enter physical characteristics. 

i left some TODOs in the appropriate index.js files, but they're way down the road type tasks, if they need to get resolved at all

2020-01-16 04:39 UTC, conorreedy requested changes
Just a few things. Might be nothing.

2020-01-16 04:39 UTC, conorreedy commented on src/Components/CharDescription/LanguageSelections/index.js
> +        this.state = {
would we be able to just say 

`this.state = this.props.languagesDictionary `

instead of parsing out here?  It creates a more flexible coupling if we can ignore the structure of the props passed in and just assume there's a dictionary somewhere in the props passed into the constructor.

2020-01-16 04:39 UTC, conorreedy commented on src/Components/CharDescription/LanguageSelections/index.js
> +        const dummy_array_to_help_generate_correct_num_of_select_elems = _buildArrayWithThisManyItems(numOfSelectElemsToGenerate);
rofl sauce. Hungarian notation! jk I know it's temporary.

2020-01-16 04:39 UTC, conorreedy commented on src/Components/CharDescription/LanguageSelections/index.js
> +        const validLanguageOptions = this.state[ _getKeyReferenceForCorrectLanguageArray(this.props.languageOptions) ];
I might be missing something but isn't this redundant? The constructor sets this value, why change it on render?

2020-01-16 04:58 UTC, merged

2020-01-16 06:49 UTC, cusbus commented on src/Components/CharDescription/LanguageSelections/index.js
> +        const validLanguageOptions = this.state[ _getKeyReferenceForCorrectLanguageArray(this.props.languageOptions) ];
this is at least bad naming conventions. i found some other bugs post merge, so i'll take a closer look at this one and try to squash those in one commit

2020-01-16 08:17 UTC, cusbus commented on src/Components/CharDescription/LanguageSelections/index.js
> +        const dummy_array_to_help_generate_correct_num_of_select_elems = _buildArrayWithThisManyItems(numOfSelectElemsToGenerate);
i know camelCase is standard in js, but for super long vars, i find kebaaaab case to be more readable. perhaps the answer is to work on better var declarations, but that is hard.

2020-01-23 04:02 UTC, conorreedy commented on src/Components/CharDescription/LanguageSelections/index.js
> +        const dummy_array_to_help_generate_correct_num_of_select_elems = _buildArrayWithThisManyItems(numOfSelectElemsToGenerate);
++